# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: jiashun-wang/blog-v3
  auth_methods: [oauth]
  branch: master
  base_url: https://sveltia-cms-auth.1043210554.workers.dev # URL of your OAuth client

  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: '{{message}}'

media_folder: /public/images
public_folder: /images



collections:
  - name: blog
    label: 博客
    label_singular: blog
    icon: "language_pinyin"
    folder: /content/posts
    create: true
    delete: true
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: pubDate, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 描述, name: description, widget: text }
      - { label: 作者, name: author, widget: string }
      - label: 图片
        name: image
        widget: object
        fields:
          - { label: 链接, name: url, widget: string }
          - { label: 替代文本, name: alt, widget: string }
      - { label: 标签, name: tags, widget: list, field: { label: 标签, name: tag, widget: string } }
      - { label: 正文, name: body, widget: markdown }
    sortable_fields: [pubDate, title]




# Media provider features
media_libraries:
  default:
    config:
      max_file_size: 4096000 # default: Infinity
      slugify_filename: true # default: false
      transformations: # See the documentation for details

  cloudflare_r2:
    access_key_id: 852bd16c78142bd7dbf82ea2a9e7a2ee
    bucket: static
    account_id: 6739ed328656ada25d8eb1c4c033da5b
    public_url: https://edge0.cc.cd
    prefix: images/ # Optional
    jurisdiction: default # Optional; 'default' | 'eu' | 'fedramp'

  cloudinary:
    config:
      cloud_name: dbxprwscm
      api_key: 329376394623687
    output_filename_only: false
    use_transformations: true